
environment:
  provider: remote_command
  command: env | grep 'CENV_' > @env_file
  roles: server-admin
  options:
    env_file: ~/.env

bootstrap-log:
  provider: remote_command
  command: cat /var/log/bootstrap.log
  roles: server-admin
  sudo: true

update:
  provider: remote_command
  command: docker-compose pull && docker-compose up -d
  roles: server-admin

restart:
  provider: remote_command
  command: docker-compose restart @system
  roles: server-admin
  options:
    system: api

log:
  provider: remote_command
  command: docker-compose logs --tail=@count @system
  roles: server-admin
  options:
    count: 100
    system: api
